export const url_api = process.env.NEXT_PUBLIC_API?.trim()
export const model_api = process.env.NEXT_PUBLIC_MODEL_API?.trim()
export const token_access = process.env.NEXT_PUBLIC_TOKEN_ACCESS?.trim()
export const storage_user = process.env.NEXT_PUBLIC_STORAGE_USER?.trim()
export const storage_image = process.env.NEXT_PUBLIC_STORAGE_IMAGE?.trim()